# Generated by Django 5.2.7 on 2025-10-23 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoyenneSemestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], max_length=10)),
                ('annee_academique', models.CharField(default='2025-2026', max_length=9)),
                ('moyenne', models.FloatField()),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.etudiant')),
            ],
            options={
                'unique_together': {('etudiant', 'semestre', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField(help_text='Note sur 100', verbose_name='Note')),
                ('type_evaluation', models.CharField(choices=[('examen', 'Examen'), ('tp', 'Travail Pratique'), ('projet', 'Projet'), ('partiel', 'Partiel')], default='examen', max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise pour validation'), ('publiée', 'Publiée (visible étudiant)'), ('rejetée', 'Rejetée')], default='brouillon', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.cours', verbose_name='Cours')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.professeur', verbose_name='Créée par')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.etudiant', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name_plural': 'Notes',
                'ordering': ['cours', 'etudiant'],
                'unique_together': {('etudiant', 'cours', 'type_evaluation')},
            },
        ),
    ]
