# Generated by Django 5.2.7 on 2025-11-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_alter_note_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_soumission',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True, verbose_name='Motif du rejet'),
        ),
    ]
