# Generated by Django 5.2.7 on 2025-12-25 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_etudiant_annee_academique_courante_and_more'),
        ('grades', '0004_note_date_soumission_note_date_validation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriquePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_niveau', models.CharField(max_length=50)),
                ('ancien_semestre', models.CharField(max_length=10)),
                ('nouveau_niveau', models.CharField(max_length=50)),
                ('nouveau_semestre', models.CharField(max_length=10)),
                ('annee_academique', models.CharField(max_length=9)),
                ('decision', models.CharField(choices=[('admis', 'Admis'), ('redouble', 'Redouble'), ('passage_conditionnel', 'Passage conditionnel'), ('changement_semestre', 'Changement de semestre')], max_length=50)),
                ('moyenne_generale', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('date_promotion', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='accounts.etudiant')),
            ],
            options={
                'verbose_name': 'Historique de promotion',
                'verbose_name_plural': 'Historiques de promotions',
                'ordering': ['-date_promotion'],
            },
        ),
    ]
