# Generated by Django 5.2.7 on 2025-12-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_historiquepromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='annee_academique',
            field=models.CharField(blank=True, help_text='Format: 2023-2024', max_length=9, null=True, verbose_name='Année académique'),
        ),
    ]
