# Generated by Django 5.2.3 on 2025-12-29 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_cours_credits'),
        ('accounts', '0008_loginattempt_blocked'),
        ('grades', '0006_note_annee_academique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveDeNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(max_length=9)),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], max_length=10)),
                ('moyenne_semestre', models.DecimalField(decimal_places=2, max_digits=5)),
                ('moyenne_cumulee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('details_notes', models.JSONField(default=dict, help_text='Structure JSON des notes')),
                ('niveau', models.CharField(max_length=10)),
                ('statut', models.CharField(default='actif', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(auto_now=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='releves/%Y/%m/%d/')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves', to='accounts.etudiant')),
                ('faculte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.faculte')),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releves_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relevé de notes',
                'verbose_name_plural': 'Relevés de notes',
                'ordering': ['-annee_academique', 'semestre'],
                'unique_together': {('etudiant', 'annee_academique', 'semestre')},
            },
        ),
    ]
