# Generated by Django 5.2.7 on 2025-11-25 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_nomination', models.DateField(auto_now_add=True)),
                ('niveau_acces', models.CharField(choices=[('super', 'Super Administrateur'), ('academique', 'Administrateur Académique'), ('utilisateurs', 'Gestionnaire Utilisateurs')], default='utilisateurs', max_length=20)),
                ('peut_gerer_utilisateurs', models.BooleanField(default=True)),
                ('peut_gerer_cours', models.BooleanField(default=True)),
                ('peut_valider_notes', models.BooleanField(default=True)),
                ('peut_gerer_facultes', models.BooleanField(default=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
