# Generated by Django 5.2.7 on 2025-12-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_admin_user_alter_etudiant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='semestre_courant',
            field=models.CharField(choices=[('S1', 'Semestre 1 (Sept-Jan)'), ('S2', 'Semestre 2 (Fév-Juin)')], default='S1', max_length=10),
        ),
    ]
