# Generated by Django 5.2.7 on 2025-12-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_etudiant_semestre_courant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('action', models.CharField(choices=[('CREATE_STUDENT', 'Création étudiant'), ('UPDATE_STUDENT', 'Modification étudiant'), ('DELETE_STUDENT', 'Suppression étudiant'), ('CREATE_TEACHER', 'Création professeur'), ('UPDATE_TEACHER', 'Modification professeur'), ('DELETE_TEACHER', 'Suppression professeur'), ('CREATE_ADMIN', 'Création administrateur'), ('USER_LOGIN', 'Connexion utilisateur'), ('USER_LOGOUT', 'Déconnexion utilisateur'), ('LOGIN_FAILED', 'Connexion échouée'), ('CREATE_COURSE', 'Création cours'), ('UPDATE_COURSE', 'Modification cours'), ('DELETE_COURSE', 'Suppression cours'), ('CREATE_FACULTY', 'Création faculté'), ('DELETE_FACULTY', 'Suppression faculté'), ('CREATE_ANNOUNCE', 'Création annonce'), ('DELETE_ANNOUNCE', 'Suppression annonce'), ('CREATE_GRADES', 'Saisie notes (brouillon)'), ('SUBMIT_GRADES', 'Soumission notes'), ('PUBLISH_GRADES', 'Publication notes'), ('REJECT_GRADES', 'Rejet notes'), ('RESET_GRADES', 'Remise en brouillon'), ('EXPORT_DATA', 'Export données'), ('CREATE_STUDENT_FAILED', 'Échec création étudiant'), ('CREATE_TEACHER_FAILED', 'Échec création professeur'), ('CREATE_ADMIN_FAILED', 'Échec création admin')], max_length=50)),
                ('objet', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('faculte', models.CharField(blank=True, max_length=100)),
                ('cours', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': "Action d'audit",
                'verbose_name_plural': "Actions d'audit",
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='accounts_au_date_39045d_idx'), models.Index(fields=['user'], name='accounts_au_user_b2e9f3_idx'), models.Index(fields=['action'], name='accounts_au_action_f46fb0_idx'), models.Index(fields=['faculte'], name='accounts_au_faculte_2c1300_idx')],
            },
        ),
    ]
