# Generated by Django 5.2.7 on 2025-12-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auditaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='annee_academique_courante',
            field=models.CharField(default='2025-2026', max_length=9, verbose_name='Année académique'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='moyenne_generale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Moyenne générale'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='statut_academique',
            field=models.CharField(choices=[('actif', 'Actif'), ('redoublant', 'Redoublant'), ('diplome', 'Diplômé'), ('abandon', 'Abandon')], default='actif', max_length=20, verbose_name='Statut académique'),
        ),
    ]
