# Generated by Django 5.2.7 on 2025-12-27 16:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_etudiant_annee_academique_courante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='annee_academique_courante',
            field=models.CharField(default=accounts.models.get_annee_academique, max_length=9, verbose_name='Année académique'),
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('successful', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tentative de connexion',
                'verbose_name_plural': 'Tentatives de connexion',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['username', 'timestamp'], name='accounts_lo_usernam_7bd469_idx'), models.Index(fields=['ip_address', 'timestamp'], name='accounts_lo_ip_addr_4f26f9_idx')],
            },
        ),
    ]
