# Generated by Django 5.2.7 on 2025-12-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_etudiant_annee_academique_courante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
