# Generated by Django 5.2.7 on 2025-10-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('intitule', models.CharField(max_length=200)),
                ('niveau', models.CharField(choices=[('1ere', '1ère année'), ('2e', '2e année'), ('3e', '3e année'), ('4e', '4e année'), ('5e', '5e année')], max_length=10)),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], max_length=10)),
                ('credits', models.IntegerField(default=3)),
            ],
            options={
                'verbose_name_plural': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
