# Generated by Django 5.2.7 on 2025-10-23 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='professeur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'prof'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Professeur assigné'),
        ),
        migrations.AddField(
            model_name='cours',
            name='faculte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.faculte'),
        ),
        migrations.AlterUniqueTogether(
            name='cours',
            unique_together={('code', 'faculte', 'niveau', 'semestre')},
        ),
    ]
