# Generated by Django 5.2.7 on 2025-12-14 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'annonce")),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('type_annonce', models.CharField(choices=[('general', 'Générale'), ('academique', 'Académique'), ('urgence', 'Urgence'), ('evenement', 'Événement'), ('emploi', "Offre d'emploi")], default='general', max_length=20, verbose_name="Type d'annonce")),
                ('priorite', models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgence', 'Urgence')], default='normale', max_length=20, verbose_name='Priorité')),
                ('destinataire_tous', models.BooleanField(default=True, verbose_name='Pour tous')),
                ('destinataire_etudiants', models.BooleanField(default=False, verbose_name='Étudiants uniquement')),
                ('destinataire_professeurs', models.BooleanField(default=False, verbose_name='Professeurs uniquement')),
                ('destinataire_admins', models.BooleanField(default=False, verbose_name='Administrateurs uniquement')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('date_expiration', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration (optionnel)")),
                ('est_publie', models.BooleanField(default=True, verbose_name='Publié')),
                ('est_important', models.BooleanField(default=False, verbose_name='Important')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='annonces/pieces_jointes/%Y/%m/%d/', verbose_name='Pièce jointe')),
                ('image', models.ImageField(blank=True, null=True, upload_to='annonces/images/%Y/%m/%d/', verbose_name='Image illustrative')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_publiees', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('faculte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.faculte', verbose_name='Faculté concernée (optionnel)')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-date_publication', '-priorite'],
                'indexes': [models.Index(fields=['est_publie', 'date_publication'], name='academics_a_est_pub_dc3d13_idx'), models.Index(fields=['type_annonce'], name='academics_a_type_an_17ec5b_idx'), models.Index(fields=['priorite'], name='academics_a_priorit_92f76e_idx')],
            },
        ),
    ]
