# Generated by Django 5.2.7 on 2025-12-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_annonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='piece_jointe',
        ),
        migrations.AddField(
            model_name='annonce',
            name='fichier_joint',
            field=models.FileField(blank=True, null=True, upload_to='annonces/fichiers/%Y/%m/%d/', verbose_name='Fichier joint'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='priorite',
            field=models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('haute', 'Haute'), ('critique', 'Critique')], default='normale', max_length=20, verbose_name='Priorité'),
        ),
    ]
