# Generated by Django 5.2.7 on 2025-12-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_annonce_piece_jointe_annonce_fichier_joint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculte',
            name='icone',
            field=models.CharField(default='fa-university', help_text="Nom de l'icône FontAwesome (ex: fa-laptop, fa-stethoscope, fa-leaf)", max_length=30),
        ),
    ]
