# Generated by Django 5.2.7 on 2025-12-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_faculte_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='credits',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
